### ISSUE TITLE
This mod probably has a lot of bugs!

### ISSUE THREAD

**Issue by YTG1234** [YTG1234/manhunt-fabric#1]
Report all bugs here in the issue tracker!
If I don't comment on one of the bugs, feel free to tag me (@YTG1234 ). Just don't do it multiple times.

**Comment by solisj** [comment]
Crashes when adding speedrunner on 1.16.4. I'm using this with [carpet mod](https://www.curseforge.com/minecraft/mc-mods/carpet), and it crashes when using "/speedrunner set". The same thing happened when using just this mod (similar stack trace) with a second player instead of a fake carpet player, so I'm unsure what the issue could be.
`---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 12/11/20, 11:38 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'void net.minecraft.class_1657.method_26082(net.minecraft.class_1293)'
	at io.github.ytg1234.manhunt.ManhuntUtils.applyStatusEffectToPlayer(ManhuntUtils.java:78)
	at io.github.ytg1234.manhunt.init.EventListener.highlightSpeedrunner(EventListener.java:52)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:62)
	at net.minecraft.server.MinecraftServer.handler$zzf000$onEndTick(MinecraftServer.java:1763)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:853)
	at net.minecraft.server.MinecraftServer.handler$zel000$modifiedRunLoop(MinecraftServer.java:3310)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:651)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:834)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Linux (amd64) version 5.4.0-56-generic
	Java Version: 11.0.9.1, Ubuntu
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Ubuntu
	Memory: 390586144 bytes (372 MB) / 1152385024 bytes (1099 MB) up to 2015363072 bytes (1922 MB)
	CPUs: 8
	JVM Flags: 0 total; 
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.2.2
		carpet: Carpet Mod in Fabric 1.4.20
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.8.2
		fabric: Fabric API 0.28.0+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+6a2618f53a
		fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+6a2618f53a
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+ffb68a873a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
		fabric-networking-v0: Fabric Networking (v0) 0.3.0+a03e98793a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: fabric-particles-v1 0.2.2+6a2618f53a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.2+a03e98793a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.2+1944f3e03a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.1+f1d8af063a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricloader: Fabric Loader 0.10.8
		manhunt: Manhunt Fabric 1.0.0
		manhunt-api: Manhunt API 1.0.0
		minecraft: Minecraft 1.16.4
	Player Count: 2 / 20; [class_3222['pikmin6000'/364, l='ServerLevel[world]', x=-124.70, y=69.00, z=144.75], EntityPlayerMPFake['Alex'/369, l='ServerLevel[world]', x=-123.70, y=68.00, z=146.07]]
	Data Packs: vanilla, fabric/fabric-tool-attribute-api-v1, file/Manhunt datapack 1.16 (incompatible)
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)`

**Comment by YTG1234** [comment]
oh lol, I'm just stupid, I'll fix it and release a version. @solisj

**Comment by YTG1234** [comment]
@solisj Fixed in [Version 1.0.1](https://modrinth.com/mod/@manhunt-fabric/version/Dfzp0oBk)
