### ISSUE TITLE
Bug issue

### ISSUE THREAD

**Issue by FandeMastk** [YTG1234/manhunt-fabric#14]
It's says that I require another mod for the manhunt. This is what the message says:
"Could not find required mod: manhunt requires {manhunt-base @ [*]}"
![Screenshot 2021-05-26 210959](https://user-images.githubusercontent.com/24800578/119754948-d1c19b00-be66-11eb-8dac-5296ac3e2f05.png)

**Comment by YTG1234** [comment]
Fabric's error messages are very weird here. Perhaps you're missing a dependency of `manhunt-base`? Make sure you have installed FLK.

**Comment by YTG1234** [comment]
This issue has been inactive for too long. Closing.
